### ISSUE TITLE
Output not documented

### ISSUE THREAD

**Issue by lucasgonze** [SecureStackCo/actions-sbom#1]
Problem: in the Github Marketplace page for this action, the location and name of the output file is not stated.

This is problematic because I am trying to understand how to use this in bundling a release. Is the output written back into the repo?

**Comment by justinabrahms** [comment]
From what I understand, the securestack saas aims to be the central storage engine for sbom data, so they don't output it.. they upload it to their own service.

**Comment by 6mile** [comment]
Heya guys, @justinabrahms is correct that by default we save the SBOM file in our central storage but the SBOM action will also output the SBOM file in the action workflow log as you can see here:  https://github.com/NiftyBank/niftybank-app/actions/runs/5075052197/jobs/9115934580

If you want you can write this to an artifact or do anything else you want with it.  Lemme know if you have any other questions!

**Comment by justinabrahms** [comment]
Can you document that output behavior? I didn't see it on the marketplace thing.

**Comment by 6mile** [comment]
heya @justinabrahms and @lucasgonze I've updated the README so check out the Marketplace listing now:  https://github.com/marketplace/actions/securestack-sbom

**Comment by lucasgonze** [comment]
Thanks, @6mile. That's a big help. 

See https://gist.github.com/lucasgonze/b84a2c52c697bf8f686a005080c369dd for the context of this conversation.
